# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				axolotl = true
				salmon = true
				zombie_villager = true
				boat = true
				skeleton = true
				area_effect_cloud = true
				bat = true
				leash_knot = true
				zombie = true
				cod = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				drowned = true
				spider = true
				creeper = true
				sheep = true
				player = true
				enderman = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.naturalist]
				deer = true
				firefly = true
				duck = true

			[light_sources.settings.entities.easy_npc]
				chicken = true
				humanoid = true
				cat = true

			[light_sources.settings.entities.handcrafted]
				seat = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true

			[light_sources.settings.entities.artifacts]
				mimic = true

