# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wither_skeleton = true
				ocelot = true
				item_frame = true
				horse = true
				leash_knot = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				blaze = true
				piglin = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				wolf = true
				villager = true
				zombie_villager = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.easy_npc]
				chicken = true
				humanoid = true
				cat = true

			[light_sources.settings.entities.handcrafted]
				seat = true

			[light_sources.settings.entities.fetzisasiandeco]
				koi = true

			[light_sources.settings.entities.vinery]
				mule = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				rhino = true
				bluejay = true
				snake = true
				boar = true
				robin = true
				duck_egg = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				firefly = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				elephant = true
				finch = true

			[light_sources.settings.entities.immersive_aircraft]
				cargo_airship = true
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

			[light_sources.settings.entities.ad_astra]
				tier_1_rocket = true

