
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				hoglin = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wandering_trader = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				vindicator = true
				horse = true
				minecart = true
				glow_squid = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				wolf = true
				villager = true
				zombie_villager = true
				boat = true
				strider = true
				hopper_minecart = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.easy_npc]
				chicken = true
				humanoid = true
				cat = true

			[light_sources.settings.entities.man_of_many_planes]
				scarlet_biplane = true

			[light_sources.settings.entities.fetzisasiandeco]
				koi = true
				fixed_seat = true

			[light_sources.settings.entities.vinery]
				mule = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.naturalist]
				deer = true
				rattlesnake = true
				zebra = true
				snail = true
				canary = true
				firefly = true
				rhino = true
				bluejay = true
				snake = true
				coral_snake = true
				cardinal = true
				lion = true
				boar = true
				robin = true
				bass = true
				giraffe = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				elephant = true
				lizard = true
				finch = true

			[light_sources.settings.entities.exposure]
				photograph_frame = true

			[light_sources.settings.entities.smallships]
				drakkar = true

			[light_sources.settings.entities.immersive_aircraft]
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				bullet = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true
				contraption = true
				super_glue = true

			[light_sources.settings.entities.supplementaries]
				hat_stand = true
				red_merchant = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

			[light_sources.settings.entities.ad_astra]
				ice_spit = true
				tier_2_rocket = true
				corrupted_lunarian = true
				tier_7_rocket = true

