name: Package the Create Modpack

on:
  push:
    paths:
      - 'create/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Version Number from Changelog
        id: determine_version
        run: |
          CHANGELOG_FILE=$(ls create/changelogs/version-*.txt | sort -V | tail -n 1)
          if [ -z "$CHANGELOG_FILE" ]; then
            echo "No changelog file found."
            exit 1
          fi
          VERSION=$(basename $CHANGELOG_FILE .txt | sed 's/version-//')
          echo "current_version=$VERSION" >> $GITHUB_ENV

      - name: Update Version in modrinth.index.json
        run: |
          jq --arg version "$CURRENT_VERSION" '.versionId = $version' create/modrinth.index.json > create/modrinth.index.json.tmp && mv create/modrinth.index.json.tmp create/modrinth.index.json
  
      - name: Update Version in manifest.json
        run: |
          jq --arg version "$CURRENT_VERSION" '.version = $version' create/manifest.json > create/manifest.json.tmp && mv create/manifest.json.tmp create/manifest.json

      - name: Set Up Build Directory
        run: |
          mkdir -p build
          cd create
          zip -r ../build/cogworks-create.zip overrides/ modlist.html manifest.json modrinth.index.json
          cd ..

      - name: Collect Changelogs from File
        run: |
          CHANGELOG_FILE="create/changelogs/version-${{ env.current_version }}.txt"
          if [ -f $CHANGELOG_FILE]; then
            CHANGELOGS=$(cat $CHANGELOG_FILE | jq -sRr @uri)
            echo "changelogs=$CHANGELOGS" >> $GITHUB_ENV
          else
            echo "Changelog file $CHANGELOG_FILE does not exist."
            exit 1
          fi

      - name: Update Changelog in README
        run: |
          echo "Current Version: ${{ env.current_version }}"
          echo "Changelogs: ${{ env.changelogs }}"
          node -e "
            const fs = require('fs');
            const path = require('path');
            const querystring = require('querystring');

            const currentVersion = process.env.current_version;
            const changelogs = querystring.unescape(process.env.changelogs);

            const readmePath = path.join(__dirname, 'create', 'readme.md');
            const readmeContent = fs.readFileSync(readmePath, 'utf8');

            const updatedContent = readmeContent.replace(
              /## Changelog[\\s\\S]*?## Support/,
              \`## Changelog\\n**Version \${currentVersion}**:\\n\\\`\\\`\\\`diff\\n\${changelogs}\\n\\\`\\\`\\\`\\nYou can checkout the [previous changelogs here](https://github.com/cogworksmc/modpacks/tree/main/create/changelogs)\\n\\n## Support\`
            );

            fs.writeFileSync(readmePath, updatedContent);
          "
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add create/readme.md
          git commit -m "Update changelog for version ${{ env.current_version }} " || echo "No changes to commit"
          git push

      - name: Upload Modpack to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Create Release v${{ env.current_version }}"
          tag_name: "Create-v${{ env.current_version }}"
          body: |
            **Changelogs:**
            ```diff
            ${{ env.changelogs }}
            ```
            
            [Download the latest version here](https://cdn.cogworksmc.com/modpacks/cogworks-create.zip)
          generate_release_notes: true
          make_latest: true
          files: build/cogworks-create.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Configure Wrangler
        run: |
          wrangler login
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Upload to Cloudflare R2
        run: |
          wrangler r2 object put cogworks/modpacks/cogworks-create.zip --file build/cogworks-create.zip
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      
      # Disabled ATM
      # - name: Upload Modpack to CurseForge
      #   run: |
      #     curl -X POST "https://minecraft.curseforge.com/api/projects/1181366/upload-file" \
      #     -H "x-api-token: ${{ secrets.CURSEFORGE_API_TOKEN }}" \
      #     -F "file=@build/cogworks-create.zip" \
      #     -F "metadata={\"changelog\":\"${{ env.changelogs }}\",\"changelogType\":\"markdown\",\"releaseType\":\"release\"}" \
      #     -F "gameVersions=[\"1.20.1\"]"
      
      - name: Notify Success
        run: echo "Modpack successfully built & uploaded to GitHub, Cloudflare R2"

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "embeds": [{
                       "title": "Version ${{ env.current_version }} has been released!",
                       "description": "**Changelogs**\n```diff\n${{ env.changelogs }}\n```\nDownload the latest version [here](https://cdn.cogworksmc.com/modpacks/cogworks-create.zip)",
                       "author": {
                         "name": "Cogworks",
                         "icon_url": "https://cogworksmc.com/CogworksLogo.gif"
                       },
                       "color": 16753920
                     }]
                   }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
