name: Package the Create Modpack

on:
  push:
    paths:
      - 'create/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Build Directory
        run: |
          mkdir -p build
          zip -r build/create-modpack.zip ./create/overrides/ ./create/manifest.json ./create/modrinth.index.json

      - name: Determine Version Number
        id: determine_version
        run: |
          VERSION_FILE="create/version.txt"
          if [ ! -f $VERSION_FILE ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          CURRENT_VERSION=$(cat $VERSION_FILE)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Update Version in modrinth.index.json
        run: |
          jq --arg version "$CURRENT_VERSION" '.versionId = $version' create/modrinth.index.json > create/modrinth.index.json.tmp && mv create/modrinth.index.json.tmp create/modrinth.index.json
  
      - name: Update Version in manifest.json
        run: |
          jq --arg version "$CURRENT_VERSION" '.version = $version' create/manifest.json > create/manifest.json.tmp && mv create/manifest.json.tmp create/manifest.json

      - name: Collect Changelogs Using Tags
        run: |
          CHANGELOG_FILE="create/changelogs/version-${{ env.current_version }}.txt"
          if [ -f $CHANGELOG_FILE ]; then
            CHANGELOGS=$(cat $CHANGELOG_FILE)
            echo "changelogs=$CHANGELOGS" >> $GITHUB_ENV
          else
            echo "Changelog file $CHANGELOG_FILE does not exist."
            exit 1
          fi

      - name: Update Changelog in README
        run: |
          awk '/## Changelog/{flag=1;next}/## Support/{flag=0}flag' create/readme.md > temp_readme.md
          awk 'NR==FNR{if (/## Changelog/) {print;print "**Version '${{ env.current_version }}'**:\n```diff\n'${{ env.changelogs }}'\n```\nYou can checkout the [previous changelogs here](https://github.com/cogworksmc/modpacks/tree/main/create/changelogs)";next}1}1' temp_readme.md create/readme.md > updated_readme.md
          mv updated_readme.md create/readme.md
          rm temp_readme.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add create/readme.md
          git commit -m "Update changelog for version ${{ env.current_version }}"
          git push

      - name: Upload Modpack to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Create Release v${{ env.current_version }}"
          tag_name: "Create-v${{ env.current_version }}"
          body: "**Changelogs:** ```diff\n${{ env.changelogs }}\n```\n\n\n[Download the latest version here](https://cdn.cogworksmc.com/modpacks/create-modpack.zip)"
          generate_release_notes: true
          make_latest: true
          files: build/create-modpack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Configure Wrangler
        run: |
          wrangler login
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Upload to Cloudflare R2
        run: |
          wrangler r2 object put cogworks/modpacks/create-modpack.zip --file build/create-modpack.zip
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Notify Success
        run: echo "Modpack successfully built & uploaded to GitHub and Cloudflare R2!"

      - name: Send Discord Notification
        run: |
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "embeds": [{
                       "title": "Version ${{ env.current_version }} has been released!",
                       "description": "**Changelogs**\n```diff\n${{ env.changelogs }}\n```\n\nDownload the latest version [here](https://cdn.cogworksmc.com/modpacks/create-modpack.zip)",
                       "author": {
                         "name": "Cogworks",
                         "icon_url": "https://cogworksmc.com/CogworksLogo.gif"
                       },
                       "color": 16753920,
                       "timestamp": "'"$CURRENT_TIME"'"
                     }]
                   }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}