name: Package the Create Modpack

on:
  push:
    paths:
      - 'create/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Build Directory
        run: |
          mkdir -p build
          zip -r build/create-modpack.zip ./create/overrides/ ./create/manifest.json ./create/modrinth.index.json

      - name: Upload Modpack to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Create Release v1.0.${{ github.run_number }}"
          tag_name: "Create-v1.0.${{ github.run_number }}"
          generate_release_notes: true
          make_latest: true
          files: build/create-modpack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Configure Wrangler
        run: |
          wrangler login
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Upload to Cloudflare R2
        run: |
          wrangler r2 object put cogworks/modpacks/create-modpack.zip --file build/create-modpack.zip
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Notify Success
        run: echo "Modpack successfully built & uploaded to GitHub and Cloudflare R2!"