name: Package the Create Modpack

on:
  push:
    paths:
      - 'create/**'
  workflow_dispatch:

jobs:
  package-modpacks:
    runs-on: ubuntu-24.04
    name: Build, Upload, and Release Modpacks

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Version Number from Changelog
        id: determine_version
        run: |
          CHANGELOG_FILE=$(ls create/changelogs/version-*.diff | sort -V | tail -n 1)
          if [ -z "$CHANGELOG_FILE" ]; then
            echo "No changelog file found."
            exit 1
          fi
          VERSION=$(basename "$CHANGELOG_FILE" .diff | sed 's/version-//')
          echo "Determined version: $VERSION"
          echo "$VERSION" > version.txt

      - name: Collect Changelogs from File
        run: |
          VERSION=$(cat version.txt)
          CHANGELOG_FILE="create/changelogs/version-${VERSION}.diff"
          if [ -f "$CHANGELOG_FILE" ]; then
            cat "$CHANGELOG_FILE" > changelogs.txt
          else
            echo "Changelog file $CHANGELOG_FILE does not exist."
            exit 1
          fi

      - name: Update modrinth.index.json with Version
        run: |
          VERSION=$(cat version.txt)
          jq --arg version "$VERSION" '.versionId = $version' create/modrinth/modrinth.index.json > create/modrinth/modrinth.index.json.tmp
          mv create/modrinth/modrinth.index.json.tmp create/modrinth/modrinth.index.json

      - name: Create Build Directory and Archive Modrinth
        run: |
          mkdir -p build
          cd create/modrinth
          zip -r ../../build/cogworks-create-modrinth.mrpack overrides/ modlist.html manifest.json modrinth.index.json
          cd ../..

      - name: Create Archive CurseForge
        run: |
          cd create/curseforge
          zip -r ../../build/cogworks-create-curseforge.zip overrides/ modlist.html manifest.json
          cd ../..

      - name: Upload Modrinth Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogworks-create-modrinth
          path: build/cogworks-create-modrinth.mrpack

      - name: Upload CurseForge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogworks-create-curseforge
          path: build/cogworks-create-curseforge.zip

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Authenticate Wrangler
        run: wrangler login
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Upload Modrinth to Cloudflare R2
        run: |
          wrangler r2 object put cogworks/modpacks/cogworks-create-modrinth.mrpack --file build/cogworks-create-modrinth.mrpack
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Upload CurseForge to Cloudflare R2
        run: |
          wrangler r2 object put cogworks/modpacks/cogworks-create-curseforge.zip --file build/cogworks-create-curseforge.zip
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Create-v${{ steps.determine_version.outputs.version || 'unknown' }}
          name: Create Release v${{ steps.determine_version.outputs.version || 'unknown' }} (CurseForge and Modrinth)
          body_path: changelogs.txt
          files: |
            build/cogworks-create-curseforge.zip
            build/cogworks-create-modrinth.mrpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        run: |
          VERSION=$(cat version.txt)
          CHANGELOGS=$(cat changelogs.txt)

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content 'Hey <@&1329954969268523139>' \
                          --arg title "Create Modpack v$VERSION has been released!" \
                          --arg description "**Changelogs:**\n\n\`\`\`diff\n$(echo "$CHANGELOGS" | sed 's/$/\\n/' | tr -d '\n')\n\`\`\`\n[Download the latest CurseForge version here](https://cdn.cogworksmc.com/modpacks/cogworks-create-curseforge.zip)\n[Download the latest Modrinth version here](https://cdn.cogworksmc.com/modpacks/cogworks-create-modrinth.mrpack)" \
                          --argjson color 16753920 \
                          '{content: $content, embeds: [{title: $title, color: $color, description: $description}]}')" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
